flask_app/blueprint_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, g, current_app
from uuid import uuid4
import sqlite3

try:
  from flask_app.do_email import send_quiz_link_email, send_feedback_link_email
except:
  from ..flask_app.do_email import send_quiz_link_email, send_feedback_link_email


page_bp = Blueprint('page', __name__, template_folder='templates')


def get_db():
  if 'db' not in g:
    db = sqlite3.connect(current_app.config['DATABASE_PATH'])
    db.cursor().executescript(open('db_init.sql').read())
    g.db = db

  return g.db

@page_bp.route("/")
def index():
  print('blueprint trying its best')
  return render_template('index.html')

@page_bp.route("/create")
def create():
  return render_template("create.html")

@page_bp.route("/teacher/quiz/<teacher_uuid>/grade", methods=["GET", "POST"])
def grade_quiz(teacher_uuid):
  if request.method == "GET":
    db = get_db()
    cursor = db.cursor()
    student_uuid, quiz_id = cursor.execute("SELECT student_uuid, id FROM quiz WHERE teacher_uuid=?", (teacher_uuid,)).fetchone()

    question_hashes = load_quiz_question_hashes(cursor, quiz_id)

    answers = cursor.execute(
      """
      SELECT 
        answer.id, 
        answer.student_id, 
        answer.minor_index, 
        answer.response_1,
        feedback.score,
        feedback.correct_answer,
        student.name
      FROM answer 
      LEFT JOIN feedback
        ON feedback.answer_id = answer.id
      LEFT JOIN student
        ON answer.student_id = student.id
      WHERE quiz_id=?
      ORDER BY answer.id, feedback.id
      """,
      (quiz_id,)
    ).fetchall()

    for qh in question_hashes:
      qh['answers'] = {
        a[0]: {
          'id': a[0],
          'student_id': a[1],
          'response_1': a[3],
          'score': a[4],
          'correct_answer': a[5],
          'student name': a[6],
        }
        for a in answers
        if a[2] == qh['minor_index']
      }

    quiz_headers = load_quiz_headers(cursor, quiz_id)

    print("qh", question_hashes)
    return render_template('grade.html', teacher_uuid=teacher_uuid, student_uuid=student_uuid, questions=question_hashes, quiz_headers=quiz_headers)

  if request.method == "POST":
    db = get_db()
    cursor = db.cursor()

    parsed_form = {}

    for key, val in request.form.items():
      split_key = key.split("-")
      parsed_form[split_key[1]] = parsed_form.get(split_key[1], {})
      if len(split_key) == 2:
        _, answer_id = split_key
        parsed_form[answer_id]['score'] = val
      if len(split_key) == 3:
        _, answer_id, metadata_type = split_key
        if metadata_type == "correct":
          parsed_form[answer_id]['correct'] = val

    parsed_arr = [[answer_id, data['score'], data['correct']] for answer_id, data in parsed_form.items()]
    cursor.executemany("INSERT INTO feedback (answer_id, score, correct_answer) VALUES (:answer_id, :score, :correct_answer)", parsed_arr)
    db.commit()
    return redirect(url_for('page.teacher_finished', teacher_uuid=teacher_uuid))

@page_bp.route("/teacher/quiz/<teacher_uuid>/finished")
def teacher_finished(teacher_uuid):
  return render_template('finished.html')

@page_bp.route("/teacher/quiz/<teacher_uuid>/links")
def quiz_links(teacher_uuid):
  db = get_db()
  cursor = db.cursor()
  student_uuid = cursor.execute("SELECT student_uuid FROM quiz WHERE teacher_uuid=?", (teacher_uuid,)).fetchone()[0]
  return render_template('links.html', teacher_uuid=teacher_uuid, student_uuid=student_uuid)

@page_bp.route("/student/quiz/<student_uuid>/take")
def take_quiz(student_uuid):
  db = get_db()
  cursor = db.cursor()
  quiz_id = cursor.execute("SELECT id FROM quiz WHERE student_uuid=?", (student_uuid,)).fetchone()[0]
  questions = load_quiz_questions(cursor, quiz_id)
  quiz_headers = load_quiz_headers(cursor, quiz_id)

  
  return render_template("take_quiz.html", student_uuid=student_uuid, questions=questions, quiz_headers=quiz_headers)

@page_bp.route("/student/quiz/<student_uuid>/submit", methods=["POST"])
def submit_quiz(student_uuid):
  parsed_form = {}
  for input_name, text in request.form.items():
    form_section, question_id = input_name.split("-")
    parsed_form[form_section] = parsed_form.get(form_section, {})
    parsed_form[form_section][question_id] = text

  db = get_db()
  cursor = db.cursor()

  cursor.execute(
    "INSERT INTO student (name, email) VALUES (?, ?)",
    (parsed_form['header']['student_name'], parsed_form['header']['student_email']),
  )
  student_id = cursor.lastrowid

  quiz_id = cursor.execute(
    "SELECT id FROM quiz WHERE student_uuid=?", (student_uuid,)
  ).fetchone()[0]

  cursor.executemany(
    "INSERT INTO answer (student_id, quiz_id, minor_index, response_1) VALUES (?, ?, ?, ?)",
    [(student_id, quiz_id, minor_index, response) for minor_index, response in parsed_form['question'].items()]
  )
  db.commit()

  quiz_metadata = load_quiz_headers(cursor, quiz_id=quiz_id)

  url = url_for("page.see_feedback", student_uuid=student_uuid, student_id=student_id, _external=True)
  send_feedback_link_email(
    'info@irohaforms.com', 
    parsed_form['header']['student_email'], 
    'Quiz Feedback', 
    url, 
    quiz_metadata['teacher name'], 
    quiz_metadata['quiz name']
  )
  return redirect(url_for("page.see_feedback", student_uuid=student_uuid, student_id=student_id))

@page_bp.route("/student/quiz/<student_uuid>/feedback/<student_id>", methods=["GET"])
def see_feedback(student_uuid, student_id):
  db = get_db()
  cursor = db.cursor()

  quiz_id = cursor.execute("SELECT id FROM quiz WHERE student_uuid=?", (student_uuid,)).fetchone()[0]


  student_metadata = cursor.execute("""
    SELECT
      student.name, 
      student.email
    FROM
      student
    WHERE
      student.id = ?
  """, (student_id,)).fetchone()
  student_metadata = {
    "student name": student_metadata[0],
    "student email": student_metadata[1]
  }

  question_hashes = load_quiz_question_hashes(cursor, quiz_id)

  answers = cursor.execute(
    """
    SELECT 
      answer.minor_index, 
      answer.response_1,
      feedback.score,
      feedback.correct_answer
    FROM 
      answer 
    LEFT JOIN feedback ON feedback.answer_id = answer.id
    WHERE quiz_id=? AND student_id=?
    """, 
    (quiz_id, student_id)
  ).fetchall()
  answers_hash = {answer[0]: {'response_1': answer[1], 'score': answer[2], 'correct_answer': answer[3]} for answer in answers}

  for question in question_hashes:
    question['response_1'] = answers_hash[question['minor_index']]['response_1']
    question['score'] = answers_hash[question['minor_index']]['score']
    question['correct_answer'] = answers_hash[question['minor_index']]['correct_answer']

  quiz_headers = load_quiz_headers(cursor, quiz_id)

  return render_template(
    'feedback.html', 
    questions=question_hashes, 
    quiz_headers=quiz_headers,
    student_metadata=student_metadata,
  )

@page_bp.route("/teacher/create_quiz", methods=["POST"])
def create_quiz():
  print("form:", request.form)
  out = {}
  for input_name, text in request.form.items():
    question_number, question_part = input_name.split('-')
    out[question_number] = out.get(question_number, {})
    out[question_number][question_part] = text
  
  db = get_db()
  cursor = db.cursor()
  cursor.execute(
    "INSERT INTO teacher (name, email) VALUES (?, ?)", 
    (
      out['header']['teacher_name'], 
      out['header']['teacher_email']
    )
  )
  teacher_id = cursor.lastrowid

  student_uuid = str(uuid4())
  teacher_uuid = str(uuid4())
  cursor.execute(
    "INSERT INTO quiz (name, teacher_id, student_uuid, teacher_uuid) VALUES (?, ?, ?, ?)",
    (out['header']['quiz_name'], teacher_id, student_uuid, teacher_uuid)
  )
  quiz_id = cursor.lastrowid

  questions = [val for key, val in out.items() if key.isdigit()]
  for idx, q in enumerate(questions):
    q["idx"] = idx
  query = f"INSERT INTO question (text_1, text_2, minor_index, question_type, quiz_id) VALUES (:text_1, :text_2, :idx, 'single_blank', {quiz_id})"
  cursor.executemany(query, questions)
  db.commit()

  redirect_url = url_for('page.quiz_links', teacher_uuid=teacher_uuid)
  teacher_url = url_for('page.grade_quiz', teacher_uuid=teacher_uuid, _external=True)
  student_url = url_for('page.take_quiz', student_uuid=student_uuid, _external=True)
  send_quiz_link_email("info@irohaforms.com", out['header']['teacher_email'], "Quiz Links", teacher_url, student_url, out['header']['quiz_name'])
  return redirect(redirect_url)

def load_quiz_headers(cursor, quiz_id):
  quiz_headers = cursor.execute("""
    SELECT 
      quiz.name as quiz_name, 
      teacher.name as teacher_name, 
      teacher.email as teacher_email  
    FROM quiz 
    INNER JOIN teacher ON quiz.teacher_id = teacher.id
    WHERE quiz.id = ?
  """, (quiz_id,)).fetchone()
  quiz_headers = {
    "quiz name": quiz_headers[0],
    "teacher name": quiz_headers[1],
    "teacher email": quiz_headers[2],
  }
  return quiz_headers 

def load_quiz_questions(cursor, quiz_id):
  questions = cursor.execute("""
    SELECT 
      text_1, 
      text_2, 
      minor_index 
    FROM question 
    WHERE quiz_id=?
  """, (quiz_id,)).fetchall()
  return questions
  
def load_quiz_question_hashes(cursor, quiz_id):
  questions = load_quiz_questions(cursor, quiz_id)
  question_hashes = [
    {'text_1': q[0], 'text_2': q[1], 'minor_index': q[2]}
    for q in questions
  ]
  return question_hashes

templates/arrow_bar.html
<div class="arrow-bar">
  <div class="arrow {{ 'active' if stage == 1 else ''}}">
    <div class="stack">
      <span class="arrow-header">１．穴埋め問題を作る</span>
      <span class="arrow-body">保存する前にすべての質問を入力してください。</span>
    </div>
  </div>
  <div class="arrow {{'active' if stage == 2 else 'upcoming' if stage < 2 else ''}}">
    <span class="arrow-header">２．試験を共有する</span></div>
  <div class="arrow {{'active' if stage == 3 else 'upcoming' if stage < 3 else ''}}">
    <span class="arrow-header">３．試験を採点する</span>
  </div>
  <div class="arrow {{'active' if stage == 4 else 'upcoming' if stage < 4 else ''}}">
    <span class="arrow-header">４．成績を共有する</span>
  </div>
</div>

templates/base.html
<!DOCTYPE html lang="jp">
<html>
  <head>
    <link rel="stylesheet" 
    type="text/css" 
    href="{{ url_for('static', filename='styles/styles.css')}}">
    <title>いろは</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='iroha_favicon.ico')}}">
    <script src="{{ url_for('static', filename='scripts/create_quiz_scripts.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/enabled_button.js') }}"></script>
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, minimum-scale=1">
  </head>
  <body>
    <header><span>いろはフォーム：</span><span>{% block title %}{% endblock %}</span></header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

templates/create.html
{% extends "base.html" %}
{% block title %}穴埋め問題を作る{% endblock %}
{% block content %}
  {% with stage=1 %}
  {% include "arrow_bar.html" %}
  {% endwith %}
  <form action="{{ url_for('page.create_quiz') }}" method="POST" id="make-quiz-form" class="quiz">
    <fieldset>
      <div>
        <label>試験の名前</label>
        <input type="text" id="header-quiz_name" name="header-quiz_name" oninput="trackInput('index', this.name, this.value, notEmptyValidator)">
      </div>
      <div>
        <label>先生の名前</label>
        <input type="text" id="header-teacher_name" name="header-teacher_name" oninput="trackInput('index', this.name, this.value, notEmptyValidator)">
      </div>
      <div>
        <label>先生のメールアドレス</label>
        <input type="text" id="header-teacher_email" name="header-teacher_email" oninput="trackInput('index', this.name, this.value, emailValidator)">
      </div>
    </fieldset>
    <div id="quiz-body" start="0">
      <example-quiz-question left_text="如何して日本語" right_text="勉強しているのですか？"></example-quiz-question>
      <quiz-question></quiz-question>
    </div>
    <div class="button-bar">
      <button type="button" onclick="addQuestion(event)">＋質問を追加</button>
      <button type="submit" id="submit-button" class="mega-button" disabled>
        保存する
        <span class="disabled-tooltip">試験の名前、先生の名前、先生のメールアドレスを入力してください</span>
      </input>
    </div>
  </form>
{% endblock %} 

templates/explanation.html
<h1>How it works</h1>
This is a step by step description of what you and your students will see while making, taking, and grading a quiz.
<h2>Create the Quiz</h2>
Fill-in-the-blank questions have text before and after the blank. Create the question by filling in those text boxes.
<ol>
  <li class="quiz-question">
    <div class="quiz-question-body">
      <input type="text" value="どうして日本語" disabled>
      <span class="blank-space"></span>
      <input type="text" value="勉強していますか。" disabled>
    </div>
  </li>
</ol>
<h2>Share with your Students</h2>
Once you're done, we'll give you a link. Send it to all your students. They'll see a form like this:
<fieldset>
  <div>
    <label>名前</label>
    <input type="text" id="header-student_name" name="header-student_name" value="JT Booth" disabled>
  </div>
  <div>
    <label>メールアドレス</label>
    <input type="text" id="header-student_email" name="header-student_email" value="jtbooth1@gmail.com" disabled>
  </div>
</fieldset>
<ol>
  <li class="quiz-question">
    <div class="quiz-question-body">
      I am going
      <input type="text" value="to" disabled>
      my cousin's birthday party.
    </div>
  </li>
</ol>
After they take the quiz, they'll get a link to their results page, which will be initially blank.
<h2>Grade the Quiz</h2>
Once your students have taken the quiz, you'll see a form like this.
<ol>
  <li class="quiz-question">
    I am going
    <span class="blank-space"></span>
    my cousin's birthday party.
    <table>
      <thead>
        <tr>
          <th class="grade-header-name">名前</th>
          <th class="grade-header-answer">答え</th>
          <th class="grade-header-maru">正解</th>
          <th class="grade-header-batsu">不正解</th>
          <th class="grade-header-correct">正しい答え</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td> JT </td>
          <td> <span>to</span> </td>
          <td>
            <input type="radio" value="O" checked disabled>
          </td>
          <td>
            <input type="radio" value="X" disabled>
          </td>
          <td>
            <input type="text" disabled>
          </td>
        </tr>
        <tr>
          <td> Chisa </td>
          <td> <span>at</span> </td>
          <td>
            <input type="radio" value="O" disabled>
          </td>
          <td>
            <input type="radio" value="X" checked disabled>
          </td>
          <td>
            <input type="text" value="to" disabled>
          </td>
        </tr>
      </tbody>
    </table>
  </li>  
</ol>
<h2>Students See Feedback</h2>
Once you've graded the quiz, your students can see the feedback.
<ol>
  <li class="quiz-question">
    I am going
    <input type="text" value="at" disabled>
    my cousin's birthday party.
    <div>
      <label>スコア</label>
      X
    </div>
    <div>
      <label>正しい答え</label>
      to
    </div>
  </li>
</ol>

templates/feedback.html
{% extends "base.html" %}
{% block title %}採点結果{% endblock %}
{% block content %}
<div class="quiz">
  <div class="quiz-header">
    <fieldset>
      <div>
        <label>試験の名前</label>
        <span>{{quiz_headers["quiz name"]}}</span>
      </div>
      <div>
        <label>先生の名前</label>
        <span>{{quiz_headers["teacher name"]}}</span>
      </div>
    </fieldset>
    <fieldset>
      <div>
        <label>名前</label>
        <span>{{student_metadata["student name"]}}</span>
      </div>
      <div>
        <label>メールアドレス</label>
        <span>{{student_metadata["student email"]}}</span>
      </div>
    </fieldset>
  </div>
  <ol>
  {% for q in questions %}
    <li class="quiz-question">
      {{q['text_1']}}
      <input type="text" value="{{q['response_1']}}" disabled>
      {{q['text_2']}}
      <div>
        <label>スコア</label>
        {% if q['score'] %}
        {{q['score']}}
        {% else %}
        まだ採点されていません
        {% endif %}
      </div>
      <div>
        {% if q['correct_answer'] %}
        <label>正しい答え</label>
        {{q['correct_answer']}}
        {% endif %}
      </div>
    </li>
  {% endfor %}
  </ol>
  <p>
    先生から採点終了の連絡が来たあと、お送りしたメールのリンクから採点結果を確認してください。
  </p>
</div>
{% endblock %}

templates/finished.html
{% extends "base.html" %}
{% block title %}採点終了{% endblock %}
{% block content %}
{% with stage=4 %}
{% include "arrow_bar.html" %}
{% endwith %}
<p>
  生徒に採点が終了したことを知らせてください。
</p>
<p>
  採点結果は生徒が解答送信時に受信したメール中のリンクから確認することができます。
</p>
<br>
<p>
  ご意見や、追加してほしい機能がありましたら、ぜひ下記のtwitterまでDMよろしくおねがいします！
</p>
<a href="http://twitter.com/chisa_bth">http://twitter.com/chisa_bth</a>
{% endblock %}

templates/grade.html
{% extends "base.html" %}
{% block title %}試験を採点する{% endblock %}
{% block content %}
<div class="arrow-bar">
  <div class="arrow">
    <span class="arrow-header">穴埋め問題を作る</span>
  </div>
  <div class="arrow">
    <span class="arrow-header">試験を共有する</span>
  </div>
  <div class="arrow active">
    <div class="stack">
      <span class="arrow-header">試験を採点する</span>
      <span class="arrow-body">生徒がクイズに答えたら、ここで採点します。</span>
    </div>
  </div>
  <div class="arrow upcoming">
    <span class="arrow-header">成績を共有する</span>
  </div>
</div>
<form action="{{ url_for('page.grade_quiz', teacher_uuid=teacher_uuid) }}" method="POST" class="quiz">
  <fieldset>
    <div>
      <label>試験の名前</label>
      <span>{{quiz_headers["quiz name"]}}</span>
    </div>
    <div>
      <label>先生の名前</label>
      <span>{{quiz_headers["teacher name"]}}</span>
    </div>
    <div>
      <label>先生のメールアドレス</label>
      <span>{{quiz_headers["teacher email"]}}</span>
    </div>
  </fieldset>
  <ol>
  {% for q in questions %}
    <li class="quiz-question">
      {{q['text_1']}}
      <span class="blank-space"></span>
      {{q['text_2']}}
      <table>
        <thead>
          <tr>
            <th class="grade-header-name">名前</th>
            <th class="grade-header-answer">答え</th>
            <th class="grade-header-maru">正解</th>
            <th class="grade-header-batsu">不正解</th>
            <th class="grade-header-correct">正しい答え</th>
          </tr>
        </thead>
        <tbody>
        {% for student_id, a in q['answers'].items() %}
          <tr>
            <td>
              {{a['student name']}} 
            </td>
            <td>
              <span>{{a['response_1']}}</span>
            </td>
            <td>
              <input 
                type="radio" 
                name="a-{{a['id']}}"
                id="a-{{a['id']}}-maru"
                value="⭕️"
                {% if a['score'] == "⭕️" %}checked{% endif %}
              >
            </td>
            <td>
              <input 
                type="radio" 
                name="a-{{a['id']}}"
                id="a-{{a['id']}}-batsu"
                value="❌"
                {% if a['score'] == "❌" %}checked{% endif %}
              >
            </td>
            <td>
              <input
                type="text"
                name="a-{{a['id']}}-correct"
                id="a-{{a['id']}}-correct"
                {% if a['correct_answer'] %} value="{{a['correct_answer']}}" {% endif %}
              >
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </li>  
  {% endfor %}
  </ol>
  <button type="submit" class="mega-button">採点を終了する</button>
</form>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}ホーム{% endblock %}
{% block content %}
<h1>簡単に穴埋め問題を作成・共有・採点しよう！</h1>
<p>
  オンラインで簡単に穴埋め問題を作成できます。作成した問題のリンクを生徒にEメール・LINE等で共有し、オンライン上で一括採点します。
</p>
<p>
  <!-- eventually figure out how to make create work properly here -->
  <button class="mega-button" onclick="window.location.href='/create'">
    問題を作成する
  </button>
</p>
{% endblock %}

templates/links.html
{% extends "base.html" %}
{% block title %}試験を共有する{% endblock %}
{% block content %}

{% with stage=2 %}
{% include "arrow_bar.html" %}
{% endwith %}
<div class="linkbox">
  <label>下記の課題のリンクを生徒にEメール・LINEなどで共有してください。</label>
  <a href="{{ url_for('page.take_quiz', student_uuid=student_uuid) }}">http://irohaforms.com{{ url_for('page.take_quiz', student_uuid=student_uuid) }}</a>
</div>
<div class="linkbox">
  <label>生徒が回答したあと、下記のリンクから採点してください。</label>
  <a href="{{ url_for('page.grade_quiz', teacher_uuid=teacher_uuid) }}">http://irohaforms.com{{ url_for('page.grade_quiz', teacher_uuid=teacher_uuid) }}</a>
</div>
<p>
  以上のリンクはメールでもお送りしています。
</p>
{% endblock %}

templates/take_quiz.html
{% extends "base.html" %}
{% block title %}解答する{% endblock %}
{% block content %}
<form action="{{ url_for('page.submit_quiz', student_uuid=student_uuid) }}" method="POST" class="quiz">
  <div class="quiz-header">
    <fieldset>
      <div>
        <label>試験の名前</label>
        <span>{{quiz_headers["quiz name"]}}</span>
      </div>
      <div>
        <label>先生の名前</label>
        <span>{{quiz_headers["teacher name"]}}</span>
      </div>
    </fieldset>
    <fieldset>
      <div>
        <label>名前</label>
        <input type="text" id="header-student_name" name="header-student_name"  oninput="trackInput('take_quiz', this.name, this.value, notEmptyValidator)">
      </div>
      <div>
        <label>メールアドレス</label>
        <input type="text" id="header-student_email" name="header-student_email"  oninput="trackInput('take_quiz', this.name, this.value, emailValidator)">
      </div>
    </fieldset>
  </div>
  <ol>
    {% for q in questions %}
    <li class="quiz-question">
      <div class="quiz-question-body">
        {{q[0]}}
        <input type="text" name="question-{{q[2]}}"> 
        {{q[1]}}
      </div>
    </li>
    {% endfor %}
  </ol>
  <button type="submit" id="submit-button" class="mega-button" disabled>
    保存する
    <span class="disabled-tooltip">名前とメールアドレスを入力してください</span>
  </button>
</form>
{% endblock %}